### ISSUE TITLE
Mod crashes minecraft

### ISSUE THREAD

**Issue by aninusmuffin** [ScoppyTech/WorldEditItems#6]
When i try to get the items form the creative inventory (when i hover over it) the game crashes.
Minecraft 1.19, Fabric Loader 0.14.8, WorldEdit 7.2.11-beta-01+6200-0877589

**Comment by e-splat** [comment]
hello! thank you for reporting, i have tried to replicate your problem and i have it too, i think that the mod is not ready for 1.19. i will update it soon

**Comment by e-splat** [comment]
hi, i have tried many things for fix that annoying bug, but nothing i can't :(. sorry....
